In [1]:
import numpy as np
import cv2

In [2]:
img=cv2.imread('./data/friends.jpg')


cv2.imshow('image',img)
cv2.waitKey()
cv2.destroyAllWindows()

In [3]:
haar=cv2.CascadeClassifier('./data/haarcascade_frontalface_default.xml')

In [7]:
image=img.copy()

gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

face_rect=haar.detectMultiScale(gray,1.3,5)

for x,y,w,h in face_rect:
    cv2.rectangle(image,(x,y),(x+w,y+h),(0,255,0),2)
    
cv2.imshow('detectionimg',image)
cv2.waitKey()
cv2.destroyAllWindows()

In [5]:
print(face_rect)

[[149 259  30  30]
 [126   4  68  68]
 [128 107  96  96]
 [255  90  95  95]
 [407  92  95  95]]


In [6]:
print(img.shape)

(399, 612, 3)
